name: run-integ-tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build CDK
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: CDK BUILD
        run: yarn build
  run-integ-tests:
    environment: integ-test-workflow-env
    name: run integ tests
    runs-on: ubuntu-latest
    steps:
    - name: submit integ test suite run
      # this needs to wait until the cached build is available...
      # can use $GITHUB_SHA to get the last commit hash on the PR
      run: |
        curl --header "Content-Type: application/json" --request POST \
        --data '{"prNumber":${{ github.event.number }}}' \
        https://cha3gpm0dk.execute-api.eu-west-3.amazonaws.com/prod/
