name: run integ tests

on:
  issue_comment:                                     
    types:
      - created
      - edited

jobs:
  run-integ-tests:
    name: run integ tests
    #if: ${{ (github.event.issue.pull_request) && (github.event.issue.state == 'open') && contains(github.event.comment.body, 'run them tests') }}
    runs-on: ubuntu-latest
    steps:
    - name: submit integ test run
      # this needs to wait until the cached build is available...WOOOOOOOOOo
      run: |
        curl --header "Content-Type: application/json" --request POST \
        --data '{"prNumber":${{ github.event.number }}}' \
        https://cha3gpm0dk.execute-api.eu-west-3.amazonaws.com/prod/
